### ISSUE TITLE
Ambiguous license.

### ISSUE THREAD

**Issue by LinArcX** [morealaz/ir-standard-fonts#1]
Hi. i want to know what is the license of these fonts?
Are they free?

**Comment by morealaz** [comment]
Hi,
these fonts belongs to Iran Supreme Council of Information and Communication Technology (SCICT) (شورای عالی اطلاع رسانی) which are no longer in existence. I just upload these fonts here because there is no longer any official source available for them . I just want them to be available for every one. As much as I know these were free to use for every one, but I don't know what type of license they have or even Are they have any license at all?

**Comment by LinArcX** [comment]
Thank you for explanations dear @morealaz :)

**Comment by mehdisadeghi** [comment]
<div dir="rtl">
من هم همین سوال برام پیش اومد. اشتباه نکنم بیشتر این فونت‌ها کپی برابر اصل فونت‌های برنارایانه هستند. یعنی احتمالا دزدی هستند و فقط اسمشون تغییر کرده. گمان نمی‌کنم بین این شورای عالی اطلاع‌رسانی و برنارایانه هم توافقی برای انتشار این فونت‌ها وجود داشته باشه.
</div>

**Comment by morealaz** [comment]
من خودم خیلی وقت هست که از این فونت ها استفاده نمیکنم. همونجور که قبلا گفتم اینها رو صرفا اینجا به این دلیل آپلود کردم چون منبع اصلی اونها دیگه وجود نداره

**Comment by mehdisadeghi** [comment]
<div dir="rtl">
@morealaz دستت درد نکنه! من صرفا جهت اطلاع سایر بازدیدکنندگان این مورد رو نوشتم. وگرنه تو زحمتی که شما کشیدی حرفی نیست :)
</div>
